code/PRN231_Project/PRN231_Client/Models/ErrorViewModel.cs
namespace PRN231_Client.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

code/PRN231_Project/PRN231_Client/Controllers/ComicsController.cs
using Microsoft.AspNetCore.Mvc;
using PRN231_API.Models;
using System.Net.Http.Headers;
using System.Text.Json;

namespace PRN231_Client.Controllers
{
    public class ComicsController : Controller
    {
        private HttpClient client;
        private string comicApiUrl = "";
        private string pageApiUrl = "";
        private string chapterApiUrl = "";
        public ComicsController() {
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            comicApiUrl = "http://localhost:5278/api/Comics";
            pageApiUrl = "http://localhost:5278/api/Pages";
            chapterApiUrl = "http://localhost:5278/api/Chapters";
        }
        private async Task<List<T>> GetDataObject<T>(string Apiurl)
        {
            using (var respone = await client.GetAsync(Apiurl))
            {
                if (respone.IsSuccessStatusCode)
                {
                    var strData = await respone.Content.ReadAsStringAsync();
                    return JsonSerializer.Deserialize<List<T>>(strData, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                }
                return new List<T>();
            }
        }
        public async Task<IActionResult> Index(int ComicId)
        {
            using(var respone = await client.GetAsync($"{comicApiUrl}/{ComicId}"))
            {
                if (respone.IsSuccessStatusCode)
                {
                    var strData = await respone.Content.ReadAsStringAsync();
                    var comic = JsonSerializer.Deserialize<Comic>(strData, new JsonSerializerOptions { PropertyNameCaseInsensitive = true});
                    return View(comic);
                }
                return NotFound("Can't found your request!");
            }
        }
        //[Route("Comics/{ComicId}/{ChapterId}")]
        public async Task<IActionResult> Chapter(int ComicId, int ChapterId)
        {
            var page = await GetDataObject<Page>($"{pageApiUrl}/{ChapterId}");
            ViewData["Chapters"] = await GetDataObject<Chapter>($"{chapterApiUrl}/{ComicId}");
            return View(page);
        }
    }
}

code/PRN231_Project/PRN231_Client/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PRN231_API.Dtos;
using PRN231_API.Helpers;
using PRN231_API.Models;
using PRN231_Client.Models;
using System.Diagnostics;
using System.Net.Http.Headers;
using System.Text.Json;

namespace PRN231_Client.Controllers
{
    public class HomeController : Controller
    {
        private HttpClient client;
        private string comicApiUrl = "";
        private string userApiUrl = "";
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            comicApiUrl = "http://localhost:5278/api/Comics";
            userApiUrl = "http://localhost:5278/api/Users";
        }
        private async Task<List<T>> GetDataObject<T>(string Apiurl)
        {
            using (var respone = await client.GetAsync(Apiurl))
            {
                if (respone.IsSuccessStatusCode)
                {
                    var strData = await respone.Content.ReadAsStringAsync();
                    return JsonSerializer.Deserialize<List<T>>(strData, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                }
                return new List<T>();
            }
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            List<Comic> comics = await GetDataObject<Comic>($"{comicApiUrl}/page/{page}");
            return View(comics);
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginForm login)
        {
            if (ModelState.IsValid)
            {
                using(var respone = await client.PostAsJsonAsync($"{userApiUrl}/Login", login))
                {
                    if (respone.IsSuccessStatusCode)
                    {
                        var strData = await respone.Content.ReadAsStringAsync();
                        var user = JsonSerializer.Deserialize<User>(strData, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                        HttpContext.Session.SetObjectAsJson("user", user);
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            return View();
        }
        public ActionResult Logout()
        {
            HttpContext.Session.Remove("user");
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(UserDTO userDTO)
        {
            if (ModelState.IsValid)
            {
                using (var respone = await client.PostAsJsonAsync($"{userApiUrl}", userDTO))
                {
                    if (respone.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Login));
                    }
                }
            }
            return View();
        }
       
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

code/PRN231_Project/PRN231_Client/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using PRN231_API.Dtos;
using PRN231_API.Helpers;
using PRN231_API.Models;
using System.Net.Http.Headers;
using System.Text.Json;

namespace PRN231_Client.Controllers
{
    public class UserController : Controller
    {
        private readonly HttpClient client;
        private string userApiUrl = "";
        private string comicApiUrl = "";

        public UserController()
        {
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            userApiUrl = "http://localhost:5278/api/Users";
            comicApiUrl = "http://localhost:5278/api/Comics";
        }

        public async Task<ActionResult> Profile()
        {
            var user = HttpContext.Session.GetObjectFromJson<User>("user");
            if (user == null) return RedirectToAction("Login", "Home");
            using (var respone = await client.GetAsync($"{userApiUrl}/{user.UserId}"))
            {
                if (respone.IsSuccessStatusCode)
                {
                    var strData = await respone.Content.ReadAsStringAsync();
                    user = JsonSerializer.Deserialize<User>(strData, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                    HttpContext.Session.SetObjectAsJson("user", user);
                    return View(user);
                }
                return RedirectToAction("Login", "Home");
            }
        }

        [HttpPost]
        public async Task<ActionResult> UploadComic(ComicDTO comicDTO)
        {
            using(var respone = await client.PostAsJsonAsync($"{comicApiUrl}", comicDTO))
            {
                    return RedirectToAction(nameof(Profile));
            }
        }
    }
}

code/PRN231_Project/PRN231_Client/Views/Comics/Chapter.cshtml
@model IEnumerable<PRN231_API.Models.Page>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- Thêm thư viện Select2 -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-rc.0/js/select2.min.js"></script>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-lg-top opacity-75">
    <div class="container">
        <a class="navbar-brand" href="#">One Punch man</a>

        <div>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <button class="btn btn-danger">
                        <i class="ti ti-chevron-left"></i>
                    </button>
                </li>
                <li class="nav-item mx-2">
                    <select class="form-select" id="selectChapter">
                        @foreach (var chapter in ViewBag.Chapters)
                        {
                            <option>
                          Chương  @chapter.ChapterNumber
                        </option>
                        }
                    </select>
                </li>
                <li class="nav-item">
                    <button class="btn btn-danger">
                        <i class="ti ti-chevron-right"></i>
                    </button>
                </li>
            </ul>
        </div>
        <div id="loadFollow">
          <button id="follow" class="btn btn-success">
            <i class="ti ti-bookmark"></i>
            Theo dõi
          </button>
          <button id="unfollow" class="btn btn-outline-danger text-wrap">
            <i class="ti ti-x"></i>Bỏ theo dõi
          </button>
          </div>
    </div>
</nav>
<div class="container">
    <h1 class="text-center my-5">Chapter 1 - Truyện tranh</h1>

    <div class="d-flex flex-column align-items-center align-content-center gap-2">
        @foreach(var item in @Model){
                <div class="page" style="border: 1px solid black;">
                  @{
                        string imgData = Convert.ToBase64String(item.Image);
                    }
                    <img src="@string.Format("data:image/jpeg;base64,{0}", imgData)"
                 class="img-fluid"
                 alt=""
                 style=" max-width: 100%;
        height: auto;" />
        </div>
        }
    </div>
</div>
<script>
    // Khởi tạo Select2 cho thẻ select
    $('#selectChapter').select2({
        // Giới hạn độ cao của danh sách tùy chọn
        dropdownCssClass: 'select2-dropdown',
    });
</script>

code/PRN231_Project/PRN231_Client/Views/Home/Index.cshtml
@model IEnumerable<PRN231_API.Models.Comic>
@{
    ViewData["Title"] = "Home Page";
}
<div class="listManga container">
    <div class="bg-light py-3 px-4 mt-5 rounded-3 position-relative"
         id="index-item-0">
        <h4 class="mb-3 py-3 text-uppercase border-bottom border-dark">
            mới cập nhật
        </h4>
        <div class="d-flex flex-wrap gap-3">
            @foreach(var item in @Model)
            {
                <div class="card border-0"
                style="
                width: 11.5rem;
                min-height: 300px;
                box-shadow: rgba(136, 165, 191, 0.48) 6px 2px 16px 0px,
                  rgba(255, 255, 255, 0.8) -6px -2px 16px 0px;
              ">
                    @{
                        string imgData = Convert.ToBase64String(item.Image);
                    }
                    <img src="@string.Format("data:image/jpeg;base64,{0}", imgData)"
                     class="card-img-top object-fit-fill"
                     style="
                  min-height: 200px;
                  height: 200px;
                  max-height: 200px;
                  background-color: antiquewhite;
                "
                     alt="loading..." />
                <div class="p-1">
                    <div class="card-body p-0">
                        <h5 class="card-title"
                            style="
                      max-width: 200px;
                      white-space: nowrap;
                      overflow: hidden;
                      text-overflow: ellipsis;
                    ">
                            <a class="text-dark text-decoration-none" asp-controller="Comics" asp-action="index" asp-route-ComicId="@item.ComicId">@item.ComicName</a>
                            
                        </h5>
                    </div>
                    <ul class="list-group p-0 list-group-flush">
                       @foreach(var chap in item.Chapters.OrderByDescending(o => o.ChapterNumber).Take(3).ToList()){
                            <li class="list-group-chapter p-0 border-0">
                            <a class="text-dark text-decoration-none" asp-controller="Comics" asp-action="Chapter" asp-route-ComicId="@item.ComicId" asp-route-chapterId="@chap.ChapterId">Chapter @chap.ChapterNumber</a>
                            <small class="text-body-secondary text-muted">@chap.PublicDate.ToString("dd/MM/yyyy")</small>
                        </li>
                       }
                        
                    </ul>
                </div>
            </div>
            }
        </div>
        <nav aria-label="Page" class="">
            <ul class="pagination mt-3 justify-content-center">

            </ul>
        </nav>
    </div>
    <div class="bg-light m-5 rounded-3"
         style="max-height: 800px"
         id="index-item-1">
        <h4 class="m-3 py-3 text-uppercase border-bottom border-dark">
            nổi bật 
        </h4>

@*        <div class="container">
            <div class="noibat">
                @foreach (var popular in ViewBag.popular)
                {
                    <div class="card mb-3 border-0 border-bottom"
                         style="max-width: 540px">
                        <div class="row g-0">
                            <div class="col-md-4">
                                @{
                                    string imgData = Convert.ToBase64String(popular.MangaImage);
                                    var image = string.Format("data:image/jpeg;base64,{0}", imgData);
                                }
                                <img class="img-fluid object-fit-fill"
                                     src="@image"
                                     style="
                        min-height: 100px;
                        height: 100px;
                        min-width: 100px;
                        background-color: antiquewhite;
                      "
                                     alt="loading..." />
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title"
                                        style="
                          max-width: 200px;
                          white-space: nowrap;
                          overflow: hidden;
                          text-overflow: ellipsis;
                        ">
                                        <a class="text-dark text-decoration-none" asp-controller="Manga" asp-action="index" asp-route-mangaId="@popular.MangaId">@popular.MangaName</a>
                                    </h5>
                                    <p class="card-text m-0">@popular.TotalChapter</p>
                                    <p class="card-text">
                                        <small class="text-body-secondary">Last updated 3 mins ago</small>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>*@
@*    <div class="my-5 bg-light rounded-3" id="index-item-2">
        <h4 class="m-3 p-1 w-75 text-uppercase border-bottom border-dark">
            Tác giả
        </h4>
        <div class="container">
            <div class="lstAuthor w-75">
                @foreach (var author in ViewBag.Author)
                {
                    <div class="card my-3 border-0 border-bottom">
                        <div class="row g-0">
                            <div class="col-4">
                                @{
                                    var image = "";
                                    if (author.Avatar != null)
                                    {
                                        var imgData = Convert.ToBase64String(author.Avatar);
                                        image = string.Format("data:image/jpeg;base64,{0}", imgData);
                                    }
                                    else image = Url.Content("~/img/avatar.jpg");

                                }
                                <img class="img-fluid object-fit-fill rounded-circle"
                                     src="@image"
                                     style="
                        min-height: 100px;
                        height: 100px;
                        min-width: 100px;
                        max-width: 100px;
                        background-color: antiquewhite;
                        border-radius: 50%;
                      "
                                     alt="loading..." />
                            </div>
                            <div class="col-8 d-flex align-items-center">
                                <div class="card-body">
                                    <h5 class="card-title text-truncate mb-0"
                                        style="max-width: 200px">Tên tác giả @author.UserName</h5>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <p class="card-text m-0">@author.Mangas.Count Truyện đã đăng</p>
                                        <small class="text-muted">Last updated 3 mins ago</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>*@
</div>
  <script>
    let params = new URLSearchParams(window.location.search);
    let CurrentPage = parseInt(params.get("page")) || 1;
    let TotalPage;
    $(document).ready(async function () {
      TotalPage = await getTotalPages();
      ShowAllPages();
      async function getTotalPages() {
        var result = await $.ajax({
          url: "http://localhost:5278/api/Comics/totalPage",
          type: "get",
          contentType: "application/json; charset=utf-8",
          dataType: "json",
        });
        return parseInt(result);
      }
      function ShowAllPages() {
        $(".pagination").empty();
        params.set("page", Math.max(1, CurrentPage - 1));
        $(".pagination").append(
          $('<li class="page-item">').addClass(CurrentPage == 1 ? "disabled" : "").append(
            $('<a class="page-link" href="?' + params.toString() + '">')
              .html("Previous")
          )
        );
        for (var i = 1; i <= TotalPage; i++) {
          params.set("page", i);
          var appendElement = $(".pagination")
            .append(
              $('<li class="page-item">').addClass(CurrentPage == i ? "active" : "").append(
                $('<a class="page-link" href="?' + params.toString() + '">')
                  .html(i)
              )
            )
            .last();
        }
        params.set("page", Math.min(TotalPage, CurrentPage + 1));
        $(".pagination").append(
          $('<li class="page-item">').addClass(CurrentPage == TotalPage ? "disabled" : "").append(
            $('<a class="page-link" href="?' + params.toString() + '">')
              .html("Next")
          )
        );
        $(".page-link").on("click", function (e) {
          e.preventDefault();
          if ($(this).html() === "Previous") {
            CurrentPage = Math.max(1, CurrentPage - 1);
          } else if ($(this).html() === "Next") {
            CurrentPage = Math.min(TotalPage, CurrentPage + 1);
          } else {
            CurrentPage = parseInt($(this).html());
          }
          params.set("page", CurrentPage);
          window.location.search = params.toString();
        });
      }
    });
  </script>

code/PRN231_Project/PRN231_Client/Views/Home/Login.cshtml
@model PRN231_API.Dtos.LoginForm

@{
    ViewData["Title"] = "Login";
}

<h1>Đăng nhập</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" requied/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label">Mật khẩu</label>
                <input asp-for="Password" type="password" class="form-control" requied />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group my-3">
                <input type="submit" value="Đăng nhập" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

code/PRN231_Project/PRN231_Client/Views/Home/Register.cshtml
@model PRN231_API.Dtos.UserDTO

@{
    ViewData["Title"] = "Register";
}

<h1>Đăng ký</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label">Mật khẩu</label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label">Vai trò</label>
                    <select asp-for="Role" class="form-control">
                        <option value="User">Người dùng</option>
                        <option value="Author">Tác giả</option>
                    </select>
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group my-3">
                <input type="submit" value="Đăng ký" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

code/PRN231_Project/PRN231_Client/Views/Shared/_Layout.cshtml
@using PRN231_API.Models
@{ 
    var tabler = "https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css";
    var user = HttpContextAccessor.HttpContext.Session.GetObjectFromJson<User>("user");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRN231_Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PRN231_Client.styles.css" asp-append-version="true" />
        <link rel="stylesheet" href="@tabler" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <!-- Thêm thư viện toastr.js -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
  <header>
    <nav
      class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow sticky-top"
    >
      <div class="container-fluid">
        <a
          class="navbar-brand"
          asp-area=""
          asp-controller="Home"
          asp-action="Index"
          >Client</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target=".navbar-collapse"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="navbar-collapse collapse d-sm-inline-flex justify-content-between"
        >
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <a
                class="nav-link text-dark"
                asp-area=""
                asp-controller="Home"
                asp-action="Index"
                >Trang chủ</a>
            </li>
  <li class="nav-item ms-lg-3">
              <div class="search navbar-text">
                <button class="btnSearch">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="icon icon-tabler icon-tabler-search"
                    width="20"
                    height="20"
                    viewBox="2 2 24 24"
                    stroke-width="2"
                    stroke="currentColor"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"></path>
                    <path d="M21 21l-6 -6"></path>
                  </svg>
                </button>
                <input
                  type="search"
                  id="searchInput"
                  placeholder="Tìm kiếm..."
                />
                <div class="position-relative">
                  <ul
                    class="bg-light p-4 rounded-3 d-none"
                    style="
                      list-style: none;
                      max-height: 200px;
                      overflow: auto;
                      position: absolute;
                      top: 100%;
                      left: 0;
                      right: 0;
                      box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
                    "
                    id="resultList"
                  ></ul>
                </div>
              </div>
            </li>
          </ul>
          <ul class="navbar-nav">
              @if(user == null){
              <li class="nav-item">
              <a
                class="nav-link text-dark"
                asp-area=""
                asp-controller="Home"
                asp-action="Login"
                
             >Đăng nhập</a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link text-dark"
                asp-area=""
                asp-controller="Home"
                asp-action="Register"
                >Đăng ký</a>
            </li>
              }else{
              <li class="nav-item">
              <a
                class="nav-link text-dark"
                asp-area=""
                asp-controller="User"
                asp-action="Profile"
                >Hello, @user.Email</a>
            </li>
              <li class="nav-item">
              <a
                class="nav-link text-dark"
                asp-area=""
                asp-controller="Home"
                asp-action="Logout"
                >Đăng xuất</a>
            </li>
                  <p></p>
              }

          </ul>
        </div>
      </div>
    </nav>
    <div class="Category px-5 py-2">
      <ul id="categoryList" class="nav"></ul>
    </div>
  </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @if(user != null){ <span id="userId">@user.UserId</span> } - PRN231_Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>